BACKGROUND = 'images/desert_background.jpeg'
TANK_1_IMAGE = 'images/desert_tank.png'
TANK_2_IMAGE = 'images/green_tank.png'
TANK_1_WEIGHTS = 'Agents/trained_agent_1.pth'
TANK_2_WEIGHTS = 'Agents/trained_agent_2.pth'
TANK_1_SAVE_WEIGHTS = 'Agents/trained_agent_1'
TANK_2_SAVE_WEIGHTS = 'Agents/trained_agent_2'
BULLET_IMAGE = 'images/bullet.png'